---
- name: Install Credstash
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

  - name: ensure latest pip version
    pip:
      name: pip
      state: latest

  - name: ensure credstash is installed
    pip:
      name: credstash
      state: latest
      extra_args: --user

  - name: ensure pip installed binaries are on PATH
    copy:
      dest: ~/.bashrc.d/pip.sh
      src: pip.sh
