---
- name: Install Docker
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
  - name: ensure docker dependencies are installed
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    become: true

  - name: ensure Docker's GPG key is added
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
    become: true

  - name: ensure Docker repository is added
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      update_cache: yes
    become: true

  - name: ensure docker is installed
    apt:
      name: docker-ce
      state: latest
    become: true

  # group { 'docker':
  #   ensure => 'present',
  # } ->

  # exec { "user in group":
  #   unless => "/bin/grep -q 'docker\\S*$userhome::user' /etc/group",
  #   command => "/usr/sbin/usermod -aG docker $userhome::user",
  # }
